[package]
name = "bevy_spine"
version = "0.1.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = "0.2"
bevy = { version = "0.8", default-features = false, features = [ "render", "bevy_asset" ] }

[dev-dependencies]
bevy_egui = "0.16"
rfd = "0.10"
lerp = "0.4"
bevy = { default-features = true }
