[package]
name = "bevy_spine"
version = "0.4.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = { version = "0.5" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "978f7cd8bf9423961f663725cba18fb3ed75b46d", default-features = false, features = [ "bevy_render", "bevy_asset", "bevy_sprite" ] }
bevy_math = { git = "https://github.com/bevyengine/bevy", rev = "978f7cd8bf9423961f663725cba18fb3ed75b46d", features = [ "mint" ] }

[dev-dependencies]
lerp = "0.4"
bevy = { git = "https://github.com/bevyengine/bevy", rev = "978f7cd8bf9423961f663725cba18fb3ed75b46d", default-features = true }

[features]
workaround_5732 = []
