[package]
name = "bevy_spine"
version = "0.4.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = { version = "0.5" }
bevy = { version = "0.9", default-features = false, features = [ "render", "bevy_asset" ] }
bevy_math = { version = "0.9", features = [ "mint" ] }

[dev-dependencies]
lerp = "0.4"
bevy = { version = "0.9", default-features = true }
