[package]
name = "bevy_spine"
version = "0.2.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = { git = "https://github.com/jabuwu/rusty_spine", rev = "9136c7b2ed46aac00dbfb3b9b6c75e7122bbd085" }
bevy = { version = "0.8", default-features = false, features = [ "render", "bevy_asset" ] }
glam = { version = "0.21", features = ["mint"] }

[dev-dependencies]
bevy_egui = "0.16"
rfd = "0.10"
lerp = "0.4"
bevy = { version = "0.8", default-features = true }

[features]
egui_debugger = [ "rusty_spine/egui_debugger" ]
