[package]
name = "bevy_spine"
version = "0.4.0-dev"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = { git = "https://github.com/jabuwu/rusty_spine", rev = "b7d4c103ea89e85a4e6eae7114eedd66f3b78d1a" }
bevy = { version = "0.9", default-features = false, features = [ "render", "bevy_asset" ] }
bevy_math = { version = "0.9", features = [ "mint" ] }

[dev-dependencies]
lerp = "0.4"
bevy = { version = "0.9", default-features = true }
